name: Java CI with Docker

on:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Docker network and MongoDB
        run: |
          docker network create --driver bridge se-methods
          docker pull mongo
          docker run -d --name mongo-dbserver --network se-methods mongo

      - name: Build with Maven
        run: mvn package

      - name: Build Docker Image
        run: docker build -t semethods-app .

      - name: Run Docker Container
        run: docker run --network se-methods --name seMethods-app semethods-app

      - name: View Logs
        run: docker logs seMethods-app